version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
