version: "3"
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpres
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - network
volumes:
  mariadb_data:
  wordpress_data:
networks:
  network:
    driver: bridge